version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      # Install dependencies needed for running tests
      - npm i npm@latest -g
      - npm install

      # Upgrade AWS CLI to the latest version
      # - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      # - npm test
  build:
    commands:
      - npm run-script build
      # Use AWS SAM to package the application by using AWS CloudFormation
      # - aws s3 cp --recursive public/ s3://$WEBSITE_S3_BUCKET/public/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      # - sed -i -e "s|assets/|$WEBSITE_S3_PREFIX/public/assets/|g" public/index.html
      # - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
  post_build:
    commands:
      - aws s3 sync ./public s3://s3.eu-central-1.amazonaws.com/elasticbeanstalk-eu-central-1-403039540759

artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d) 
  base-directory: public